### ISSUE TITLE
Correctly format output data from Jetson Nano

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S4-SiemLucassen-SmartHome#11]
**Learning goal(s)**
Goal: I want to determine what output data is important for storing in the database, and how to get it in the correct format for posting it to the API.
Result:
Determine what output data is important in a correct format:
-     image frames (bitmap array)
-     accuracy of model
-     date & time of detection
-     number of detections

**Task(s)**
- [ ] Determine what output data is important to us
- [ ] Generate all the output data
- [ ] Correctly format output data
