### ISSUE TITLE
As a homeowner, I want the data to be stored in a database and have access to it, for showing detection data.

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S4-SiemLucassen-SmartHome#18]
**Acceptance Criteria**
- DB string must be stored in environment variables

**Tasks**
- [x] Add PostgreSQL Database
- [x] Add Prisma ORM
- [x] Set up API with Next
