### ISSUE TITLE
As a homeowner, I want to see the cat detection log, so I know when my cat has been detected to open the window door

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S4-SiemLucassen-SmartHome#8]
**Acceptance Criteria**
- [x] Should show detections of the cat by date & time in cat preview component

**Test cases**
- [x] TC01 click on button in the detection log component

**Tasks**
- [x] Create Cat detection log component
- [x] Create Cat preview component
- [x] Call the endpoint for sensor data
- [x] Show detections by data & time in the Cat detector tab
