### ISSUE TITLE
As a homeonwer, I want see a live view of the camera mounted on the sensor board, so I can get notified if I need to open the door for my cat

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S4-SiemLucassen-SmartHome#9]
**Acceptance Criteria**
- [ ] Should show live view of the camera mounted on the sensor board.

**Tasks**
- [ ] Create Live view component
- [ ] Call the endpoint for sensor data
- [ ] Show live view in the Cat detector tab
